2023-07-07 14:52:44.354462: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
INFO flwr 2023-07-07 14:52:48,829 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-07-07 14:52:48,832 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-07-07 14:52:48,833 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-07-07 14:52:48,910 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2023-07-07 14:52:50,936 | connection.py:113 | gRPC channel closed
Traceback (most recent call last):
  File "client_3.py", line 147, in <module>
    main()
  File "client_3.py", line 142, in main
    fl.client.start_numpy_client(server_address="10.30.0.254:9000",
  File "/home/s124m21/.local/lib/python3.8/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/home/s124m21/.local/lib/python3.8/site-packages/flwr/client/app.py", line 178, in start_client
    client_message, sleep_duration, keep_going = handle(
  File "/home/s124m21/.local/lib/python3.8/site-packages/flwr/client/message_handler/message_handler.py", line 67, in handle
    return _fit(client, server_msg.fit_ins), 0, True
  File "/home/s124m21/.local/lib/python3.8/site-packages/flwr/client/message_handler/message_handler.py", line 126, in _fit
    fit_res = maybe_call_fit(
  File "/home/s124m21/.local/lib/python3.8/site-packages/flwr/client/client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/s124m21/.local/lib/python3.8/site-packages/flwr/client/app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "client_3.py", line 109, in fit
    mnist.train(self.model, self.trainloader, epochs=1, device=DEVICE)
  File "/home/s124m21/projekat_DDU/novo_fedavg/mnist.py", line 110, in train
    outputs = net(images)
  File "/home/s124m21/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/s124m21/projekat_DDU/novo_fedavg/mnist.py", line 34, in forward
    x = self.pool(F.relu(self.conv1(x)))
  File "/home/s124m21/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/s124m21/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/s124m21/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
srun: error: n02: task 0: Exited with exit code 1
