2023-07-10 11:31:53.607892: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
INFO flwr 2023-07-10 11:31:58,139 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-07-10 11:31:58,141 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-07-10 11:31:58,142 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-07-10 11:31:58,143 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2023-07-10 11:39:16,526 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-07-10 11:39:16,733 | connection.py:113 | gRPC channel closed
Traceback (most recent call last):
  File "client_4.py", line 213, in <module>
    main()
  File "client_4.py", line 208, in main
    fl.client.start_numpy_client(server_address="10.30.0.254:9000",
  File "/home/s124m21/.local/lib/python3.8/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/home/s124m21/.local/lib/python3.8/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/home/s124m21/.local/lib/python3.8/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/opt/miniconda3/lib/python3.8/site-packages/grpc/_channel.py", line 475, in __next__
    return self._next()
  File "/opt/miniconda3/lib/python3.8/site-packages/grpc/_channel.py", line 881, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:10.30.0.254:9000 {grpc_message:"Socket closed", grpc_status:14, created_time:"2023-07-10T11:39:16.524004566+02:00"}"
>
srun: error: n02: task 0: Exited with exit code 1
