srun: /usr/lib64/slurm/select_alps.so: Incompatible Slurm plugin version (18.08.6)
srun: error: Couldn't load specified plugin name for select/alps: Incompatible plugin version
srun: /usr/lib64/slurm/select_cray.so: Incompatible Slurm plugin version (18.08.6)
srun: error: Couldn't load specified plugin name for select/cray: Incompatible plugin version
srun: /usr/lib64/slurm/select_serial.so: Incompatible Slurm plugin version (18.08.6)
srun: error: Couldn't load specified plugin name for select/serial: Incompatible plugin version
srun: /usr/lib64/slurm/switch_cray.so: Incompatible Slurm plugin version (18.08.6)
srun: error: Couldn't load specified plugin name for switch/cray: Incompatible plugin version
2023-07-13 16:03:21.345029: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
INFO flwr 2023-07-13 16:03:27,458 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-07-13 16:03:27,460 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-07-13 16:03:27,465 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2023-07-13 16:14:39,992 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-07-13 16:15:09,331 | connection.py:113 | gRPC channel closed
Traceback (most recent call last):
  File "client_3.py", line 234, in <module>
    main()
  File "client_3.py", line 229, in main
    fl.client.start_numpy_client(server_address="10.30.0.254:9000",
  File "/home/s124m21/.local/lib/python3.8/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/home/s124m21/.local/lib/python3.8/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/home/s124m21/.local/lib/python3.8/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/opt/miniconda3/lib/python3.8/site-packages/grpc/_channel.py", line 475, in __next__
    return self._next()
  File "/opt/miniconda3/lib/python3.8/site-packages/grpc/_channel.py", line 864, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:10.30.0.254:9000 {created_time:"2023-07-13T16:14:39.990494253+02:00", grpc_status:14, grpc_message:"Socket closed"}"
>
srun: error: n05: task 0: Exited with exit code 1
