srun: /usr/lib64/slurm/select_alps.so: Incompatible Slurm plugin version (18.08.6)
srun: error: Couldn't load specified plugin name for select/alps: Incompatible plugin version
srun: /usr/lib64/slurm/select_cray.so: Incompatible Slurm plugin version (18.08.6)
srun: error: Couldn't load specified plugin name for select/cray: Incompatible plugin version
srun: /usr/lib64/slurm/select_serial.so: Incompatible Slurm plugin version (18.08.6)
srun: error: Couldn't load specified plugin name for select/serial: Incompatible plugin version
srun: /usr/lib64/slurm/switch_cray.so: Incompatible Slurm plugin version (18.08.6)
srun: error: Couldn't load specified plugin name for switch/cray: Incompatible plugin version
2023-08-22 21:26:49.166547: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
INFO flwr 2023-08-22 21:26:53,957 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-08-22 21:26:53,959 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-08-22 21:26:53,959 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-08-22 21:26:53,961 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2023-08-22 21:30:05,131 | connection.py:113 | gRPC channel closed
Traceback (most recent call last):
  File "client_7.py", line 204, in <module>
    main()
  File "client_7.py", line 199, in main
    fl.client.start_numpy_client(server_address="10.30.0.254:9000",
  File "/home/s124m21/.local/lib/python3.8/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/home/s124m21/.local/lib/python3.8/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/home/s124m21/.local/lib/python3.8/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/opt/miniconda3/lib/python3.8/site-packages/grpc/_channel.py", line 475, in __next__
    return self._next()
  File "/opt/miniconda3/lib/python3.8/site-packages/grpc/_channel.py", line 881, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:10.30.0.254:9000 {grpc_message:"Socket closed", grpc_status:14, created_time:"2023-08-22T21:30:05.124990922+02:00"}"
>
srun: error: n03: task 0: Exited with exit code 1
