2023-08-22 21:30:32.095097: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "client_3.py", line 207, in <module>
    main()
  File "client_3.py", line 186, in main
    data = torch.load('home/s124m21/projekat_DDU/homo/fedavg/data_3.pth')
  File "/home/s124m21/.local/lib/python3.8/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/s124m21/.local/lib/python3.8/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/s124m21/.local/lib/python3.8/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'home/s124m21/projekat_DDU/homo/fedavg/data_3.pth'
srun: error: n01: task 0: Exited with exit code 1
