srun: /usr/lib64/slurm/select_alps.so: Incompatible Slurm plugin version (18.08.6)
srun: error: Couldn't load specified plugin name for select/alps: Incompatible plugin version
srun: /usr/lib64/slurm/select_cray.so: Incompatible Slurm plugin version (18.08.6)
srun: error: Couldn't load specified plugin name for select/cray: Incompatible plugin version
srun: /usr/lib64/slurm/select_serial.so: Incompatible Slurm plugin version (18.08.6)
srun: error: Couldn't load specified plugin name for select/serial: Incompatible plugin version
srun: /usr/lib64/slurm/switch_cray.so: Incompatible Slurm plugin version (18.08.6)
srun: error: Couldn't load specified plugin name for switch/cray: Incompatible plugin version
2023-08-22 21:32:07.105811: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
INFO flwr 2023-08-22 21:32:11,582 | grpc.py:50 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-08-22 21:32:11,587 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-08-22 21:32:11,587 | connection.py:39 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-08-22 21:32:11,596 | connection.py:39 | ChannelConnectivity.READY
DEBUG flwr 2023-08-22 21:32:51,924 | connection.py:39 | ChannelConnectivity.IDLE
DEBUG flwr 2023-08-22 21:32:52,132 | connection.py:113 | gRPC channel closed
Traceback (most recent call last):
  File "client_5.py", line 150, in <module>
    main()
  File "client_5.py", line 144, in main
    fl.client.start_numpy_client(server_address="10.30.0.254:9000",
  File "/home/s124m21/.local/lib/python3.8/site-packages/flwr/client/app.py", line 252, in start_numpy_client
    start_client(
  File "/home/s124m21/.local/lib/python3.8/site-packages/flwr/client/app.py", line 174, in start_client
    server_message = receive()
  File "/home/s124m21/.local/lib/python3.8/site-packages/flwr/client/grpc_client/connection.py", line 105, in <lambda>
    receive: Callable[[], ServerMessage] = lambda: next(server_message_iterator)
  File "/opt/miniconda3/lib/python3.8/site-packages/grpc/_channel.py", line 475, in __next__
    return self._next()
  File "/opt/miniconda3/lib/python3.8/site-packages/grpc/_channel.py", line 881, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-08-22T21:32:51.921479905+02:00", grpc_status:14, grpc_message:"Socket closed"}"
>
srun: error: n04: task 0: Exited with exit code 1
